os: linux
language: minimal
env:
  global:
#    - SKIP_DOCKER_BUILD=true

#    - FORCE_DEPLOY_TO_GKE=true
#    - SKIP_DEPLOY_TO_GKE=true

    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

    - PROJECT_IMAGE_NAME=laboschqpa-filehost
    - SHORT_COMMIT_HASH=${TRAVIS_COMMIT::10}
    - IMAGE_NAME_COMMIT=${DOCKER_USERNAME}/${PROJECT_IMAGE_NAME}:${SHORT_COMMIT_HASH}
    - IMAGE_NAME_BRANCH=${DOCKER_USERNAME}/${PROJECT_IMAGE_NAME}:${TRAVIS_BRANCH}

install: skip
script: skip

jobs:
  include:
    - stage: DockerBuild
      if: env(SKIP_DOCKER_BUILD) != "true"
      services:
        - docker
      script: skip
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - IMAGE_NAME_LATEST=${DOCKER_USERNAME}/${PROJECT_IMAGE_NAME}
      install:
        - docker pull ${IMAGE_NAME_LATEST} || true

        - docker build -t ${IMAGE_NAME_LATEST} -t ${IMAGE_NAME_COMMIT} -t ${IMAGE_NAME_BRANCH} -f docker/Dockerfile-k8s_dev-travis_build .

        - docker push ${IMAGE_NAME_LATEST}
        - docker push ${IMAGE_NAME_COMMIT}
        - docker push ${IMAGE_NAME_BRANCH}

    - stage: DeployToGKE
      if: env(SKIP_DEPLOY_TO_GKE) != "true" AND (branch = master OR env(FORCE_DEPLOY_TO_GKE) = "true")
      script: skip
      before_install:
        - echo ${GKE_SERVICE_ACCOUNT_BASE64} | base64 --decode > gke-service-account.json
        - curl https://sdk.cloud.google.com | bash > /dev/null
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file gke-service-account.json
        - gcloud config set project ringed-bebop-312422
        - gcloud config set compute/zone europe-central2-a
        - gcloud container clusters get-credentials laboschqpa-1
        - ls -lah
      install:
        - kubectl -n=qpa set image deployments/filehost filehost=${IMAGE_NAME_COMMIT}
