FROM openjdk:11
MAINTAINER "János Gats <gatsjanos@gmail.com>"

ENV APP_HOME=/home/spring-user/app

RUN groupadd -g 10003 spring-user && \
    useradd -m -u 10003 -g spring-user spring-user

WORKDIR ${APP_HOME}

HEALTHCHECK --interval=15s \
            --retries=3 \
            --start-period=1m \
            --timeout=5s \
            CMD curl --fail http://localhost:4300 || exit 1

EXPOSE 30007
EXPOSE 4300

COPY --chown=spring-user:spring-user build/libs/laboschqpa.imageconverter.jar ${APP_HOME}/laboschqpa.imageconverter.jar

USER spring-user